<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ImmunizationSeeder extends Seeder
{

    private $immunizations = [
        [
            "name" => "Hepatitis B 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis B yang menyebabkan kerusakan hati",
            "indication" => "Bayi baru lahir,Anak belum pernah mendapat vaksin hepatitis B,\nPasien Cuci Darah (Hemodialisis),\n Pasien yang Memerlukan transfusi berulang,\nIndividu yang pekerjaannya beresiko tertular hepatitis B,\nPengguna narkoba jarum suntik,",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis B sebelumnya",
            "chase_immunization" => "Anak atau remaja yang belum pernah divaksinasi harus mendapat 3 dosis, konsultasikan dengan dokter anak",
            "KIPI" => "Reaksi lokal seperti nyeri, kemerahan, bengkak ringan, kadang disertai demam ringan",
            "schedule" => "Vaksin hepatitis B pada bayi diberikan melalui injeksi intramuskuler, yaitu dengan menyuntikkan vaksin pada area otot. Adapun dosis vaksin hepatitis B adalah sebanyak 0,5–1 ml dengan 4 kali dosis utama dan 1 kali booster.",
            "recommended_days" => 0,
        ],
        [
            "name" => "Hepatitis B 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis B yang menyebabkan kerusakan hati",
            "indication" => "Bayi baru lahir,Anak belum pernah mendapat vaksin hepatitis B,\nPasien Cuci Darah (Hemodialisis),\n Pasien yang Memerlukan transfusi berulang,\nIndividu yang pekerjaannya beresiko tertular hepatitis B,\nPengguna narkoba jarum suntik,",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis B sebelumnya",
            "chase_immunization" => "Anak atau remaja yang belum pernah divaksinasi harus mendapat 3 dosis, konsultasikan dengan dokter anak",
            "KIPI" => "Reaksi lokal seperti nyeri, kemerahan, bengkak ringan, kadang disertai demam ringan",
            "schedule" => "Vaksin hepatitis B pada bayi diberikan melalui injeksi intramuskuler, yaitu dengan menyuntikkan vaksin pada area otot. Adapun dosis vaksin hepatitis B adalah sebanyak 0,5–1 ml dengan 4 kali dosis utama dan 1 kali booster.",
            "recommended_days" => 60,
        ],

        [
            "name" => "Hepatitis B 3",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis B yang menyebabkan kerusakan hati",
            "indication" => "Bayi baru lahir,Anak belum pernah mendapat vaksin hepatitis B,\nPasien Cuci Darah (Hemodialisis),\n Pasien yang Memerlukan transfusi berulang,\nIndividu yang pekerjaannya beresiko tertular hepatitis B,\nPengguna narkoba jarum suntik,",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis B sebelumnya",
            "chase_immunization" => "Anak atau remaja yang belum pernah divaksinasi harus mendapat 3 dosis, konsultasikan dengan dokter anak",
            "KIPI" => "Reaksi lokal seperti nyeri, kemerahan, bengkak ringan, kadang disertai demam ringan",
            "schedule" => "Vaksin hepatitis B pada bayi diberikan melalui injeksi intramuskuler, yaitu dengan menyuntikkan vaksin pada area otot. Adapun dosis vaksin hepatitis B adalah sebanyak 0,5–1 ml dengan 4 kali dosis utama dan 1 kali booster.",
            "recommended_days" => 90,
        ],

        [
            "name" => "Hepatitis B 4",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis B yang menyebabkan kerusakan hati",
            "indication" => "Bayi baru lahir,Anak belum pernah mendapat vaksin hepatitis B,\nPasien Cuci Darah (Hemodialisis),\n Pasien yang Memerlukan transfusi berulang,\nIndividu yang pekerjaannya beresiko tertular hepatitis B,\nPengguna narkoba jarum suntik,",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis B sebelumnya",
            "chase_immunization" => "Anak atau remaja yang belum pernah divaksinasi harus mendapat 3 dosis, konsultasikan dengan dokter anak",
            "KIPI" => "Reaksi lokal seperti nyeri, kemerahan, bengkak ringan, kadang disertai demam ringan",
            "schedule" => "Vaksin hepatitis B pada bayi diberikan melalui injeksi intramuskuler, yaitu dengan menyuntikkan vaksin pada area otot. Adapun dosis vaksin hepatitis B adalah sebanyak 0,5–1 ml dengan 4 kali dosis utama dan 1 kali booster.",
            "recommended_days" => 90,
        ],

        [
            "name" => "Hepatitis B 5",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis B yang menyebabkan kerusakan hati",
            "indication" => "Bayi baru lahir,Anak belum pernah mendapat vaksin hepatitis B,\nPasien Cuci Darah (Hemodialisis),\n Pasien yang Memerlukan transfusi berulang,\nIndividu yang pekerjaannya beresiko tertular hepatitis B,\nPengguna narkoba jarum suntik,",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis B sebelumnya",
            "chase_immunization" => "Anak atau remaja yang belum pernah divaksinasi harus mendapat 3 dosis, konsultasikan dengan dokter anak",
            "KIPI" => "Reaksi lokal seperti nyeri, kemerahan, bengkak ringan, kadang disertai demam ringan",
            "schedule" => "Vaksin hepatitis B pada bayi diberikan melalui injeksi intramuskuler, yaitu dengan menyuntikkan vaksin pada area otot. Adapun dosis vaksin hepatitis B adalah sebanyak 0,5–1 ml dengan 4 kali dosis utama dan 1 kali booster.",
            "recommended_days" => 540,
        ],

        [
            "name" => "Polio 0",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 0,
        ],

        [
            "name" => "Polio 1",
            "type" => "OPV vaksin hidup, IPV vaksin mati",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 60,
        ],
        [
            "name" => "Polio 2",
            "type" => "OPV vaksin hidup, IPV vaksin mati",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 90,
        ],
        [
            "name" => "Polio 3",
            "type" => "OPV vaksin hidup, IPV vaksin mati",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 120,
        ],
        [
            "name" => "Polio 4 (Pengulangan)",
            "type" => "OPV vaksin hidup, IPV vaksin mati",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 540,
        ],
        [
            "name" => "Polio 5 (IPV)",
            "type" => "IPV vaksin mati",
            "prevention" => "Mencegah penyakit polio yang menyebabkan kelumpuhan",
            "indication" => "Semua bayi baru lahir",
            "contraindication" => "Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma",
            "chase_immunization" => "Saat lahir, bayi diberikan bOPV, selanjutnya diberi Polio 1, Polio 2, Polio 3, dan Polio 4 pada usia 2, 3, 4, dan 18 bulan. Pada usia 4-6 tahun, anak diberikan vaksin Polio 5 (IPV).",
            "KIPI" => "Penyakit polio akbiar OPV",
            "schedule" => "Vaksin polio diberikan melalui suntikan atau pemberian oral (minum). Pemberian vaksin polio oral (OPV) dilakukan sebanyak 4 kali, yaitu saat bayi lahir, usia 2 bulan, 3 bulan, dan 4 bulan. Pemberian vaksin polio suntikan (IPV) dilakukan sebanyak 3 kali, yaitu saat bayi berusia 2 bulan, 4 bulan, dan 18 bulan.",
            "recommended_days" => 540,
        ],
        [
            "name" => "BCG",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit tuberkulosis (TBC) yang menyerang paru-paru",
            "indication" => "Bayi usia kurang dari 3 bulan yang belum imunisasi BCG,\n bayi yang kontak erat penderita TBC Aktif dan telah mendapat pengobatan profilasksis dan hasil uji tuberkulin negatif",
            "contraindication" => "Hasil uji tuberkulin >5 mm (positif), Kondisi gangguan sistem kekebalan tubuh, seperti HIV/AIDS, leukemia, dan limfoma,\nDemam tinggi,\nRiwayat infeksi TBC,\nRiwayat alergi terhadap vaksin BCG,\nHamil",
            "chase_immunization" => "BCG diberikan pada bayi baru lahir, yaitu saat bayi berusia 0-7 hari. BCG diberikan melalui suntikan",
            "KIPI" => "Bisul ditempat penyuntikan",
            "schedule" => "BCG diberikan pada bayi baru lahir, yaitu saat bayi berusia 0-7 hari sesegera mungkin sebelum bayi berusia 1 bulan. Jika berusia lebih dari 3 bulan perlu dilakukan uji tuberkulin dan akan diberikan jika hasilnya negatif. BCG diberikan melalui suntikan",
            "recommended_days" => 0,
        ],
        [
            "name" => "DPT-HB-Hib 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit difteri, pertusis, tetanus, hepatitis B, dan infeksi Haemophilus influenzae tipe b (Hib)",
            "indication" => "Bayi usia 2 bulan yang belum pernah mendapat vaksin DPT-HB-Hib",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi DPT-HB-Hib sebelumnya",
            "chase_immunization" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "recommended_days" => 60,
        ],
        [
            "name" => "DPT-HB-Hib 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit difteri, pertusis, tetanus, hepatitis B, dan infeksi Haemophilus influenzae tipe b (Hib)",
            "indication" => "Bayi usia 2 bulan yang belum pernah mendapat vaksin DPT-HB-Hib",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi DPT-HB-Hib sebelumnya",
            "chase_immunization" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "recommended_days" => 90,
        ],
        [
            "name" => "DPT-HB-Hib 3",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit difteri, pertusis, tetanus, hepatitis B, dan infeksi Haemophilus influenzae tipe b (Hib)",
            "indication" => "Bayi usia 2 bulan yang belum pernah mendapat vaksin DPT-HB-Hib",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi DPT-HB-Hib sebelumnya",
            "chase_immunization" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "recommended_days" => 120,
        ],
        [
            "name" => "DPT-HB-Hib 4",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit difteri, pertusis, tetanus, hepatitis B, dan infeksi Haemophilus influenzae tipe b (Hib)",
            "indication" => "Bayi usia 2 bulan yang belum pernah mendapat vaksin DPT-HB-Hib",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi DPT-HB-Hib sebelumnya",
            "chase_immunization" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "recommended_days" => 540,
        ],
        [
            "name" => "DPT-HB-Hib 5",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit difteri, pertusis, tetanus, hepatitis B, dan infeksi Haemophilus influenzae tipe b (Hib)",
            "indication" => "Bayi usia 2 bulan yang belum pernah mendapat vaksin DPT-HB-Hib",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi DPT-HB-Hib sebelumnya",
            "chase_immunization" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "DPT-HB-Hib diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. DPT-HB-Hib diberikan melalui suntikan",
            "recommended_days" => 1825,
        ],
        [
            "name" => "Rotavirus 1",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit diare yang disebabkan oleh rotavirus",
            "indication" => "Bayi usia 6 minggu sampai 14 minggu yang belum pernah mendapat vaksin rotavirus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi rotavirus sebelumnya",
            "chase_immunization" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "KIPI" => "Demam, muntah, diare, dan ruam kulit",
            "schedule" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "recommended_days" => 42,
        ],
        [
            "name" => "Rotavirus 2",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit diare yang disebabkan oleh rotavirus",
            "indication" => "Bayi usia 6 minggu sampai 14 minggu yang belum pernah mendapat vaksin rotavirus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi rotavirus sebelumnya",
            "chase_immunization" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "KIPI" => "Demam, muntah, diare, dan ruam kulit",
            "schedule" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "recommended_days" => 70,
        ],
        [
            "name" => "Rotavirus 3",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit diare yang disebabkan oleh rotavirus",
            "indication" => "Bayi usia 6 minggu sampai 14 minggu yang belum pernah mendapat vaksin rotavirus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi rotavirus sebelumnya",
            "chase_immunization" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "KIPI" => "Demam, muntah, diare, dan ruam kulit",
            "schedule" => "Rotavirus diberikan pada bayi berusia 6 minggu, 10 minggu, dan 14 minggu. Rotavirus diberikan melalui mulut",
            "recommended_days" => 98,
        ],
        [
            "name" => "Pneumokokus 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit pneumonia, otitis media, dan meningitis yang disebabkan oleh bakteri pneumokokus",
            "indication" => "Bayi usia 2 bulan sampai 6 bulan yang belum pernah mendapat vaksin pneumokokus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi pneumokokus sebelumnya",
            "chase_immunization" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,\nRewel, demam, dan diare",
            "schedule" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "recommended_days" => 60,
        ],
        [
            "name" => "Pneumokokus 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit pneumonia, otitis media, dan meningitis yang disebabkan oleh bakteri pneumokokus",
            "indication" => "Bayi usia 2 bulan sampai 6 bulan yang belum pernah mendapat vaksin pneumokokus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi pneumokokus sebelumnya",
            "chase_immunization" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,\nRewel, demam, dan diare",
            "schedule" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "recommended_days" => 90,
        ],
        [
            "name" => "Pneumokokus 3",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit pneumonia, otitis media, dan meningitis yang disebabkan oleh bakteri pneumokokus",
            "indication" => "Bayi usia 2 bulan sampai 6 bulan yang belum pernah mendapat vaksin pneumokokus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi pneumokokus sebelumnya",
            "chase_immunization" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,\nRewel, demam, dan diare",
            "schedule" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "recommended_days" => 120,
        ],
        [
            "name" => "Pneumokokus Booster",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit pneumonia, otitis media, dan meningitis yang disebabkan oleh bakteri pneumokokus",
            "indication" => "Bayi usia 2 bulan sampai 6 bulan yang belum pernah mendapat vaksin pneumokokus",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi pneumokokus sebelumnya",
            "chase_immunization" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,\nRewel, demam, dan diare",
            "schedule" => "Pneumokokus diberikan pada bayi berusia 2 bulan, 3 bulan, dan 4 bulan. Pneumokokus diberikan melalui suntikan",
            "recommended_days" => 540,
        ],
        [
            "name" => "JE 1",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit Japanese encephalitis (JE) yang menyebabkan radang otak",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang tinggal di daerah endemis JE",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi JE sebelumnya",
            "chase_immunization" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "recommended_days" => 270,
        ],
        [
            "name" => "JE 2",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit Japanese encephalitis (JE) yang menyebabkan radang otak",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang tinggal di daerah endemis JE",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi JE sebelumnya",
            "chase_immunization" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "recommended_days" => 730,
        ],
        [
            "name" => "JE 3",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit Japanese en
            cephalitis (JE) yang menyebabkan radang otak",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang tinggal di daerah endemis JE",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi JE sebelumnya",
            "chase_immunization" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "recommended_days" => 330,
        ],
        [
            "name" => "JE Booster",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit Japanese encephalitis (JE) yang menyebabkan radang otak",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang tinggal di daerah endemis JE",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi JE sebelumnya",
            "chase_immunization" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "KIPI" => "Demam, nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "JE diberikan pada anak berusia 9 bulan sampai 12 bulan. JE diberikan melalui suntikan",
            "recommended_days" => 540,
        ],
        [
            "name" => "MR 1",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit campak dan gondong yang menyebabkan ruam merah di seluruh tubuh, pembengkakan kelenjar getah bening, dan demam",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang belum pernah mendapat vaksin MR",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi MR sebelumnya",
            "chase_immunization" => "MR diberikan pada anak berusia 9 bulan sampai 12 bulan. MR diberikan melalui suntikan",
            "KIPI" => "Demam, ruam merah di seluruh tubuh, batuk, pilek, dan mata berair",
            "schedule" => "MR diberikan pada anak berusia 9 bulan sampai 12 bulan. MR diberikan melalui suntikan",
            "recommended_days" => 270,
        ],
        [
            "name" => "MR/MMR 2",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit campak, gondong, dan rubella yang menyebabkan ruam merah di seluruh tubuh, pembengkakan kelenjar getah bening, dan demam",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang belum pernah mendapat vaksin MMR",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi MMR sebelumnya",
            "chase_immunization" => "MMR diberikan pada anak berusia 9 bulan sampai 12 bulan. MMR diberikan melalui suntikan",
            "KIPI" => "Demam, ruam merah di seluruh tubuh, batuk, pilek, dan mata berair",
            "schedule" => "MMR diberikan pada anak berusia 9 bulan sampai 12 bulan. MMR diberikan melalui suntikan, bilamana anak belum mendapat vaksin MR sebelumnya maka dapat diberikan MMR",
            "recommended_days" => 540,
        ],
        [
            "name" => "Varisela 1",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit cacar air yang menyebabkan ruam merah di seluruh tubuh dan demam",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang belum pernah mendapat vaksin varisela",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi varisela sebelumnya",
            "chase_immunization" => "Varisela diberikan pada anak berusia 9 bulan sampai 12 bulan. Varisela diberikan melalui suntikan",
            "KIPI" => "Demam, ruam merah di seluruh tubuh, batuk, pilek, dan mata berair",
            "schedule" => "Varisela diberikan pada anak berusia 9 bulan sampai 12 bulan. Varisela diberikan melalui suntikan",
            "recommended_days" => 365,
        ],
        [
            "name" => "Varisela 2",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit cacar air yang menyebabkan ruam merah di seluruh tubuh dan demam",
            "indication" => "Anak usia 9 bulan sampai 12 bulan yang belum pernah mendapat vaksin varisela",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi varisela sebelumnya",
            "chase_immunization" => "Varisela diberikan pada anak berusia 9 bulan sampai 12 bulan. Varisela diberikan melalui suntikan",
            "KIPI" => "Demam, ruam merah di seluruh tubuh, batuk, pilek, dan mata berair",
            "schedule" => "Varisela diberikan pada anak berusia 9 bulan sampai 12 bulan. Varisela diberikan melalui suntikan",
            "recommended_days" => 420,
        ],
        [
            "name" => "Hepatitis A 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis A yang menyebabkan gangguan fungsi hati",
            "indication" => "Anak usia 12 bulan sampai 23 bulan yang belum pernah mendapat vaksin hepatitis A",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis A sebelumnya",
            "chase_immunization" => "Dapat diberikan kapan saja dengan usia minimal 12 bulan. Hepatitis A diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Dapat diberikan kapan saja dengan usia minimal 12 bulan. Hepatitis A diberikan melalui suntikan",
            "recommended_days" => 365,
        ],
        [
            "name" => "Hepatitis A 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit hepatitis A yang menyebabkan gangguan fungsi hati",
            "indication" => "Anak usia 12 bulan sampai 23 bulan yang belum pernah mendapat vaksin hepatitis A",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi hepatitis A sebelumnya",
            "chase_immunization" => "Dapat diberikan kapan saja dengan usia minimal 12 bulan. Hepatitis A diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Dapat diberikan kapan saja dengan usia minimal 12 bulan. Hepatitis A diberikan melalui suntikan",
            "recommended_days" => 540,
        ],
        [
            "name" => "Typhoid 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit tifoid yang menyebabkan demam tinggi, sakit kepala, dan diare",
            "indication" => "Anak usia 2 tahun sampai 15 tahun yang belum pernah mendapat vaksin tifoid",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi tifoid sebelumnya",
            "chase_immunization" => "Typhoid diberikan pada anak berusia 2 tahun sampai 15 tahun. Typhoid diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Typhoid diberikan pada anak berusia 2 tahun sampai 15 tahun. Typhoid diberikan melalui suntikan",
            "recommended_days" => 730,
        ],
        [
            "name" => "Typhoid 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit tifoid yang menyebabkan demam tinggi, sakit kepala, dan diare",
            "indication" => "Anak usia 2 tahun sampai 15 tahun yang belum pernah mendapat vaksin tifoid",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi tifoid sebelumnya",
            "chase_immunization" => "Typhoid diberikan pada anak berusia 2 tahun sampai 15 tahun. Typhoid diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Typhoid diberikan pada anak berusia 2 tahun sampai 15 tahun. Typhoid diberikan melalui suntikan",
            "recommended_days" => 1825,
        ],
        [
            "name" => "Influenza 1",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 180,
        ],
        [
            "name" => "Influenza 2",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 210,
        ],
        [
            "name" => "Influenza 3",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 540,
        ],
        [
            "name" => "Influenza 4",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 730,
        ],
        [
            "name" => "Influenza 5",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 1095,
        ],
        [
            "name" => "Influenza 6",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 1460,
        ],
        [
            "name" => "Influenza 7",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 1825,
        ],
        [
            "name" => "Influenza 8",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 2190,
        ],
        [
            "name" => "Influenza 9",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 2555,
        ],
        [
            "name" => "Influenza 10",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 2920,
        ],
        [
            "name" => "Influenza 11",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 3285,
        ],
        [
            "name" => "Influenza 12",
            "type" => "vaksin mati",
            "prevention" => "Mencegah penyakit influenza yang menyebabkan demam, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 6 bulan sampai 59 bulan yang belum pernah mendapat vaksin influenza",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi influenza sebelumnya",
            "chase_immunization" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan,",
            "schedule" => "Influenza diberikan pada anak berusia 6 bulan sampai 59 bulan. Influenza diberikan melalui suntikan",
            "recommended_days" => 3650,
        ],
        [
            "name" => " Dengue 1",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit demam berdarah dengue yang menyebabkan demam tinggi, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 9 tahun sampai 16 tahun yang belum pernah mendapat vaksin dengue",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi dengue sebelumnya",
            "chase_immunization" => "Dengue diberikan pada anak berusia 9 tahun sampai 16 tahun. Dengue diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan, demam, sakit kepala, dan nyeri otot",
            "schedule" => "Dengue diberikan pada anak berusia 9 tahun sampai 16 tahun. Dengue diberikan melalui suntikan",
            "recommended_days" => 3285,
        ],
        [
            "name" => " Dengue 2",
            "type" => "vaksin hidup",
            "prevention" => "Mencegah penyakit demam berdarah dengue yang menyebabkan demam tinggi, sakit kepala, dan nyeri otot",
            "indication" => "Anak usia 9 tahun sampai 16 tahun yang belum pernah mendapat vaksin dengue",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi dengue sebelumnya",
            "chase_immunization" => "Dengue diberikan pada anak berusia 9 tahun sampai 16 tahun. Dengue diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan, demam, sakit kepala, dan nyeri otot",
            "schedule" => "Dengue diberikan pada anak berusia 9 tahun sampai 16 tahun. Dengue diberikan melalui suntikan",
            "recommended_days" => 3650,
        ],
        [
            "name" => " HPV 1",
            "type" => "vaksin rekombinan",
            "prevention" => "Mencegah penyakit kanker serviks yang menyebabkan kanker serviks",
            "indication" => "Anak perempuan usia 9 tahun sampai 13 tahun yang belum pernah mendapat vaksin HPV",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi HPV sebelumnya",
            "chase_immunization" => "HPV diberikan pada anak perempuan berusia 9 tahun sampai 13 tahun. HPV diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan, demam, sakit kepala, dan nyeri otot",
            "schedule" => "HPV diberikan pada anak perempuan berusia 9 tahun sampai 13 tahun. HPV diberikan melalui suntikan",
            "recommended_days" => 3285,
        ],
        [
            "name" => " HPV 2",
            "type" => "vaksin rekombinan",
            "prevention" => "Mencegah penyakit kanker serviks yang menyebabkan kanker serviks",
            "indication" => "Anak perempuan usia 9 tahun sampai 13 tahun yang belum pernah mendapat vaksin HPV",
            "contraindication" => "Riwayat anafilaksis setelah vaksinasi HPV sebelumnya",
            "chase_immunization" => "HPV diberikan pada anak perempuan berusia 9 tahun sampai 13 tahun. HPV diberikan melalui suntikan",
            "KIPI" => "Nyeri, kemerahan, dan bengkak di tempat suntikan, demam, sakit kepala, dan nyeri otot",
            "schedule" => "HPV diberikan pada anak perempuan berusia 9 tahun sampai 13 tahun. HPV diberikan melalui suntikan",
            "recommended_days" => 3650,
        ],

    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        foreach ($this->immunizations as $immunization) {
            \App\Models\Immunization::create($immunization);
        }
    }
}
